[package]
name = "flutter_discord_rpc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.86"
discord-rich-presence = "0.2.4"
flutter_rust_bridge = "=2.1.0"
lazy_static = "1.5.0"
