[package]
name = "flutter_discord_rpc"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"

[dependencies]
anyhow = "1.0.82"
discord-rich-presence = "0.2.3"
flutter_rust_bridge = "1.82.*"
lazy_static = "1.4.0"
