[package]
name = 'metadata_god'
version = '0.5.3'
edition = '2021'

[lib]
crate-type = ['staticlib', 'cdylib']

[[bin]]
name='main'
path='./src/main.rs'

[build-dependencies]
flutter_rust_bridge_codegen = '1.82.*'

[dependencies]
flutter_rust_bridge = '1.82.*'
anyhow = '1'
lofty = '0.19.*'