name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  build_libraries:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-latest
        platforms:
          - linux
          - android
          - windows
          - ios
          - macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2
      - uses: goto-bus-stop/setup-zig@v2
        if: ${{ matrix.platforms == 'linux' }}
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: nttld/setup-ndk@v1
        if: ${{ matrix.platforms == 'android' }}
        with:
          ndk-version: r25b

      - name: Extract project name
        id: extract
        run: |
          PROJECT_NAME=$(echo ${{ github.ref_name }} | rev | cut -d '-' -f 2- | rev)
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        shell: bash
      
      - name: Build all library binaries
        run: |
          dart cli/main.dart ${{ matrix.platforms }} -p ${{ env.PROJECT_NAME }}
        shell: bash

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Libraries
          path: platform-build/

  release:
    runs-on: ubuntu-latest
    needs: build_libraries
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Libraries
          path: platform-build/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: platform-build/**